# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: op5p01.k8.unimatrix.us
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-pvc"
      volumeName: "prometheus-pv"
  service:
    Type: LoadBalancer
    port: 80
